# Generated by Django 3.2.6 on 2021-12-09 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('child', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id',
                 models.BigAutoField(auto_created=True,
                                     primary_key=True,
                                     serialize=False,
                                     verbose_name='ID')),
                ('created_at',
                 models.DateTimeField(
                     auto_now_add=True,
                     help_text=
                     'Дата/время создания объекта, автоматически заполняется')
                 ),
                ('updated_at',
                 models.DateTimeField(
                     auto_now=True,
                     help_text=
                     'Дата/время обновления объекта, автоматически изменяется при изменении полей объекта'
                 )),
                ('deleted_at',
                 models.DateTimeField(
                     blank=True,
                     default=None,
                     help_text=
                     'Дата/время удаления объекта, рекомендуется использовать данную метку для удаления, а не SQL DELETE команду',
                     null=True)),
                ('date', models.DateField(help_text='Дата вакцинации')),
                ('name',
                 models.CharField(help_text='Название вакцины',
                                  max_length=100)),
                ('series', models.CharField(help_text='Серия', max_length=20)),
                ('quantity', models.FloatField(help_text='Доза')),
                ('reaction', models.CharField(max_length=255)),
                ('child',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to='child.child')),
            ],
            options={
                'db_table': 'vaccination',
            },
        ),
    ]
