# Generated by Django 3.2.6 on 2021-12-09 19:49

import backend.apps.core.models
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата/время создания объекта, автоматически заполняется')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Дата/время обновления объекта, автоматически изменяется при изменении полей объекта')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, help_text='Дата/время удаления объекта, рекомендуется использовать данную метку для удаления, а не SQL DELETE команду', null=True)),
                ('first_name', models.CharField(help_text='Имя человека', max_length=255)),
                ('last_name', models.CharField(help_text='Фамилия человека', max_length=255)),
                ('middle_name', models.CharField(help_text='Отчество человека', max_length=255, null=True)),
                ('snils', models.CharField(help_text='СНИЛС человека, 11 цифр', max_length=11, validators=[backend.apps.core.models.is_digit_string])),
                ('gender', models.CharField(choices=[('М', 'М'), ('Ж', 'Ж')], help_text='Пол - М/Ж', max_length=15)),
                ('birth_date', models.DateField(help_text='Дата рождения', null=True)),
                ('email', models.EmailField(db_index=True, help_text='Почта', max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Активный пользователь, может ли авторизоваться')),
                ('is_staff', models.BooleanField(default=False, help_text='Суперпользователь')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None)),
                ('send_messages', models.BooleanField(default=True, help_text='Присылать оповещения о новых событиях?')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'parent',
            },
        ),
    ]
