# Generated by Django 3.2.6 on 2021-12-12 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parent', '0002_parent_children'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='middle_name',
            field=models.CharField(blank=True,
                                   default=None,
                                   help_text='Отчество человека',
                                   max_length=255,
                                   null=True),
        ),
    ]
